---
title: "wow dps statistic"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
# runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(RSQLite)

bayes_mean <- function(dps, n) {
  dps * n / (n + mean(n)) + mean(dps) * mean(n) / (n + mean(n))
}

pal_wow <- c(
  'Hunter' = '#A9D271',
  'Shaman' = '#0070DE',
  'Warlock' = '#8787ED',
  'Mage' = '#40C7EB',
  'Death Knight' = '#C41F3B',
  'Warrior' = '#C79C6E',
  'Druid' = '#FF7D0A',
  'Demon Hunter' = '#A330C9',
  'Priest' = '#FFFFFF',
  'Paladin' = '#F58CBA',
  'Rogue' = '#FFF569',
  'Monk' = '#00FF96',
  'Other' = 'grey'
)

pal_covenant <- c(
  'nightfae' = '#c851ec',
  'venthyr' = '#e02d2d',
  'kyrian' = '#a9dcfc',
  'necrolord' = '#96b364'
)

con <- dbConnect(SQLite(), 'wcl.sqlite')
data_hist <- dbGetQuery(
  con, 
  'SELECT
     `date`, class, spec, COUNT(1) AS n
   FROM
     report
   WHERE spec <> "NA"
   AND class NOT LIKE "%specs-warcraft%"
   AND spec NOT LIKE "%specs-warcraft%"
   GROUP BY `date`, class, spec;'
) %>% 
  as_tibble()
dbDisconnect(con)

data_hist <- data_hist %>% 
  group_by(date) %>% 
  group_modify(~ {
    mutate(.x, n = n / sum(n))
  }) %>% 
  ungroup()

wcl <- readRDS('wcl_n.rds')
file_info <- file.info('wcl_n.rds')
report <- wcl$report %>% 
  tidyr::unnest(report) %>% 
  filter(
    !is.na(class), 
    !is.na(spec), 
    !stringr::str_detect(
      spec,
      'Holy|Restoration|Mistweaver|Protection|Blood|Vengeance|Discipline|Guardian|unknown|Brewmaster|,'), 
    class %in% names(pal_wow), 
    !grepl('specs-warcraft', spec)
  )

limit_top <- quantile(report$dps, 0.75, na.rm = TRUE) + 1.5 * IQR(report$dps, na.rm = TRUE)
limit_bottom <- quantile(report$dps, 0.25, na.rm = TRUE) - 1.5 * IQR(report$dps, na.rm = TRUE)
report <- filter(report, between(dps, limit_bottom, limit_top))

# wcl_m <- readRDS('wcl_m.rds')
# file_info_m <- file.info('wcl_m.rds')
# report_m <- wcl_m$report %>% 
#   tidyr::unnest(report) %>% 
#   filter(
#     !is.na(class), 
#     !is.na(spec), 
#     !stringr::str_detect(
#       spec,
#       'Holy|Restoration|Mistweaver|Protection|Blood|Vengeance|Discipline|Guardian|unknown|,')
#   )

q <- 0.75
```

page 1
=====================================================================


Row 
-----------------------------------------------------------------------

### Players 
```{r}
valueBox(n_distinct(report$name), color = 'grey', icon = 'fa-users')
```

### Dps Median
```{r}
valueBox(median(report$dps, na.rm = TRUE), color = 'grey', icon = 'fa-weight')
```

### Ilvl Median
```{r}
valueBox(median(report$ilvl, na.rm = TRUE), color = 'grey', icon = 'fa-tshirt')
```

### nightfae  
```{r}
valueBox(sum(report$covenant == 'nightfae', na.rm = TRUE), color = pal_covenant['nightfae'])
```

### venthyr  
```{r}
valueBox(sum(report$covenant == 'venthyr', na.rm = TRUE), color = pal_covenant['venthyr'])
```

### necrolord   
```{r}
valueBox(sum(report$covenant == 'necrolord', na.rm = TRUE), color = pal_covenant['necrolord'])
```

### kyrian  
```{r}
valueBox(sum(report$covenant == 'kyrian', na.rm = TRUE), color = pal_covenant['kyrian'])
```



Row 
-----------------------------------------------------------------------

### Damage Per Second in Nathria @ `r as.character(file_info$mtime)` {data-height=1000}

```{r}
data <- report %>%
  select(class, spec, dps) %>% {
    dat <- .
    
    temp <- group_by(dat, class, spec) %>%
      summarise(
        dps_median = quantile(dps, probs = q, na.rm = TRUE),
        text_pos = quantile(dps, 0.75, na.rm = TRUE), 
        n = n(),
        .groups = 'drop'
      )
    temp <- mutate(temp, dps_median = bayes_mean(dps_median, n))
    
    right_join(temp, dat, by = c('class', 'spec'))
  } %>%
  mutate(name = paste(class, spec))

# data$name <- factor(paste(data$class, data$spec), levels = arrange(data, dps_median) %>% distinct(class, spec) %>% mutate(name = paste(class, spec)) %>% pull(name))
# 
# data <- crosstalk::SharedData$new(data)
# 
# crosstalk::filter_slider('dps', 'dps', data, ~ dps)
# plot_ly(data, x = ~ dps, y = ~ name, type = 'box', color = ~ class, colors = pal_wow, showlegend = FALSE, line = list(color = 'grey', width = 1))

p <- data %>%
  ggplot(aes(reorder(name, dps_median), dps)) +
  geom_boxplot(aes(fill = class), color = 'grey', alpha = 1, show.legend = FALSE) +
  geom_text(data = distinct(data, name, dps_median, spec), aes(name, dps_median, label = spec), nudge_y = 300, alpha = 0.6, size = 3) +
  coord_flip() +
  scale_fill_manual(values = pal_wow) +
  theme_minimal() +
  labs(x = NULL)

ggplotly(p) %>%
  layout(showlegend = FALSE, yaxis = list(showticklabels = FALSE))
  
```


### summary {data-height=1000}

```{r}

data <- count(report, class, spec, sort = TRUE) %>% 
  mutate(prop = round(n / sum(n), 3) * 100, name = paste(class, spec))

p <- data %>% 
  ggplot(aes(reorder(name, n), n)) +
  geom_col(aes(fill = class), width = 0.6, color = 'gray', alpha = 1, show.legend = FALSE) + 
  geom_text(data = data, aes(name, n, label = paste(prop, spec)), nudge_y = 30, alpha = 0.6, size = 3) + 
  coord_flip() + 
  scale_fill_manual(values = pal_wow) + 
  theme_minimal() + 
  labs(x = NULL)

ggplotly(p) %>% 
  layout(showlegend = FALSE, yaxis = list(showticklabels = FALSE))
  
```

Row 
-----------------------------------------------------------------------

### Variance in Nathria {data-width=400}

```{r}
data <- report %>%
  mutate(
    dps_all = quantile(dps, q, na.rm = TRUE),
    var_all = var(dps, na.rm = TRUE)
  ) %>%
  group_by(class, spec, dps_all, var_all) %>%
  summarise(
    var = var(dps, na.rm = TRUE),
    dps = quantile(dps, q, na.rm = TRUE),
    n = n(),
    .groups = 'drop'
  )

p <- data %>% 
  ggplot(aes(dps, var)) +
  geom_point(aes(size = n ^ 2, color = class), show.legend = FALSE) +
  geom_hline(aes(yintercept = var_all), linetype = 'dashed', color = 'grey') +
  geom_vline(aes(xintercept = dps_all), linetype = 'dashed', color = 'grey') +
  geom_text(aes(dps, var, label = spec), alpha = 0.6, size = 3) + 
  scale_y_continuous(labels = function(x)format(x, scientific = TRUE)) +
  scale_color_manual(values = pal_wow) +
  theme_minimal()

ggplotly(p, tooltip = 'class') %>% 
  layout(showlegend = FALSE)

```

### item level

```{r}

# p <- report %>% 
#   ggplot(aes(ilvl, dps)) + 
#   geom_point(size = 1, alpha = 0.1, color = 'blue') + 
#   theme_minimal()
# 
# ggplotly(p) %>% 
#   layout(showlegend = FALSE)

data <- filter(report, class %in% c('Hunter', 'Death Knight', 'Paladin', 'Shaman'),
               !is.na(covenant)) %>%
  select(class, spec, covenant, dps) %>% {
    dat <- .

    temp <- group_by(dat, class, spec, covenant) %>%
      summarise(
        dps_median = quantile(dps, probs = q, na.rm = TRUE),
        text_pos = quantile(dps, 0.75, na.rm = TRUE),
        n = n(),
        .groups = 'drop'
      )
    temp <- mutate(temp, dps_median = bayes_mean(dps_median, n))

    right_join(temp, dat, by = c('class', 'spec', 'covenant'))
  } %>%
  mutate(name = paste(covenant, spec),
         name = tidytext::reorder_within(name, dps_median, class))

p <- data %>%
  ggplot(aes(name, dps)) +
  geom_boxplot(aes(fill = covenant), color = 'grey', alpha = 1, show.legend = FALSE) +
  coord_flip() +
  tidytext::scale_x_reordered() +
  facet_wrap(~ class, scales = 'free') +
  scale_fill_manual(values = pal_covenant) +
  theme_minimal() +
  labs(x = NULL) +
  theme(axis.text = element_text(size = 15),
        plot.margin = unit(c(0, 0, 0, 0), 'cm'))
p

```

page 2
=====================================================================

### trend
```{r}

p <- data_hist %>% 
  filter(date >= Sys.Date() - 30) %>% 
  mutate(name = paste(class, spec), n = round(n * 100, 2)) %>% 
  ggplot(aes(date, n)) + 
  geom_line(aes(color = class, group = name), size = 1.2) + 
  # gghighlight::gghighlight(unhighlighted_params = list(size = 1)) + 
  facet_wrap(~ name, scales = 'free') + 
  scale_color_manual(values = pal_wow) + 
  # scale_x_date(date_breaks = '1 week', date_labels = '%B') + 
  theme_minimal()

ggplotly(p, tooltip = c('n')) %>% 
  layout(showlegend = FALSE)

```

